# Generated by Django 5.2.7 on 2025-10-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='chef_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='leftover_reason',
            field=models.IntegerField(choices=[(0, '未选择'), (1, '口味问题'), (2, '分量问题'), (3, '个人原因'), (4, '菜品质量')], default=0),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='quantity_rating',
            field=models.IntegerField(choices=[(0, '未选择'), (1, '分量太大'), (2, '分量适中'), (3, '分量不足')], default=0),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='status',
            field=models.IntegerField(choices=[(0, '已收到'), (1, '已采纳'), (2, '已拒绝')], default=0),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='taste_rating',
            field=models.IntegerField(choices=[(0, '未选择'), (1, '偏咸'), (2, '偏淡'), (3, '适中')], default=0),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='texture_rating',
            field=models.IntegerField(choices=[(0, '未选择'), (1, '火候过老'), (2, '火候过嫩'), (3, '适中')], default=0),
        ),
    ]
