# Generated by Django 5.2.7 on 2025-10-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_alter_pointtransaction_survey_periodicfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leftoversubmission',
            name='photo_type',
            field=models.IntegerField(choices=[(0, '菜品照片'), (1, '剩餐照片')], default=0),
        ),
    ]
