# Generated by Django 4.2.25 on 2025-11-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="desc_zh_hk",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dish",
            name="name_zh_hk",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
